services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5430:5432"
    volumes:
      - my_pg_v:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: myuser
    container_name: gather_db

volumes:
  my_pg_v:

networks:
  default:
    name: my_custom_network
