services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5430:5432"
    volumes:
      - my_pg_v:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: postgresdev
      POSTGRES_PASSWORD: postgresdev
    container_name: gather_db_dev

volumes:
  my_pg_v:

networks:
  default:
    name: my_custom_network