services:
  postgres-test:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgrestest
      POSTGRES_PASSWORD: postgrestest
    container_name: gather_db_test

